name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Add remote 
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git remote add space https://ArissBandoss:$HF_TOKEN@huggingface.co/spaces/ArissBandoss/DeepFake-Videos-Detection
                                  
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://ArissBandoss:$HF_TOKEN@huggingface.co/spaces/ArissBandoss/DeepFake-Videos-Detection main
